branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: production-env
    group_suffix: null
environment-defaults:
  production-env:
    branch: null
    repository: null
global:
  application_name: qnaprod
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: ap-south-1
  profile: eb-cli
  repository: null
  sc: git
